### ISSUE TITLE
Deduplicate and cleanup GitHub Actions

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/gsoc#44]
Homebrew makes extensive use of GitHub Actions. Some of our workflows are pretty similar to each other and could be reused within the Homebrew organisation and community.

See more details in https://github.com/Homebrew/brew/issues/11101

**Comment by mistydemeo** [comment]
I think this'd make a good 175 hour project.

**Comment by mohzulfikar** [comment]
Hello, my name is Fikar and I'm interested in this project. Based on the description provided in README, I'll try to read the issues and homebrew docs first. I would find it very helpful if you could recommend to me pages to read about homebrew (like the flow of development or homebrew components).

**Comment by SMillerDev** [comment]
All homebrew documentation is available through docs.brew.sh.

**Comment by mistydemeo** [comment]
If you have specific questions, feel free to ask and we'll be happy to provide whatever information you need.

**Comment by mohzulfikar** [comment]
Sure thank you. So as I read and explore through the brew and core repository, seems like there is already composite action implemented in part of ci (e.g. Homebrew/actions/git-user-config@master to config git user in ci).

I see that there's several repeatable action for using `brew style` on several CI. Is this a good start point for contributing to this project? Thank you.

**Comment by MikeMcQuaid** [comment]
> So as I read and explore through the brew and core repository, seems like there is already composite action implemented in part of ci (e.g. Homebrew/actions/git-user-config@master to config git user in ci).

Doing more stuff like this would be great!

> I see that there's several repeatable action for using `brew style` on several CI. Is this a good start point for contributing to this project? Any feedback will be helpful.

That'd be great. Can you elaborate on what you're thinking here?

**Comment by dawidd6** [comment]
`git-user-config` action is not a composite action though.

**Comment by mohzulfikar** [comment]
Thank you for the answer, I would try to submit my PR for the `gsoc` requirement first and compiling the documents. From that documents we might have several thing to discuss.

**Comment by mohzulfikar** [comment]
> `git-user-config` action is not a composite action though.

Well, I think I would have to read the GitHub docs again thank you for pointing it out!

**Comment by mohzulfikar** [comment]
Hello there, sorry for keep you waiting. I have submitted the proposal for this project. Please let me know if there's any question. Thank you.

**Comment by mohzulfikar** [comment]
Following up the discussion on Homebrew/brew#11101,

I'm planning to change some CI in homebrew project. The First one that I want to be grouped with composite action is this code on `homebrew-core`.
```yaml
      - name: Failures summary for brew test-bot --only-formulae
        if: always()
        run: |
          touch bottles/steps_output.txt
          cat bottles/steps_output.txt
          rm bottles/steps_output.txt
      - name: Output brew bottle result
        if: always()
        run: |
          cat bottles/bottle_output.txt
          rm bottles/bottle_output.txt
```

The link to the action workflow is here:
1. [dispatch-rebottle](https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/dispatch-rebottle.yml)
2. [dispatch-build-bottle](https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/dispatch-build-bottle.yml)

Any additional suggestions or comments? Thank you
